// Generated by the server build before Vercel packages this function.
// @ts-expect-error The generated module does not exist during the source-only typecheck.
import app from '../.vercel-build/server/index.js';

export const maxDuration = 300;
export default app;
